//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esercizio_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int id { get; set; }
        public System.DateTime datag { get; set; }
        public string pasto { get; set; }
        public string Giorno { get; set; }
        public string primo { get; set; }
        public string secondo { get; set; }
        public string contorno { get; set; }
        public string dolce { get; set; }
    }
}
